version: '2'

services:
  payments-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/common-components/payments-api
    command: --wait-for-database 30
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-database:5432/payment
    ports:
     - 8181:8181
    links:
     - payments-database
    depends_on:
     - payments-database

  payments-database:
    build:
      context: docker/database
    image: docker.artifactory.reform.hmcts.net/common-components/payments-database
    ports:
      - 5431:5432
